### PR TITLE
Add database support for aoi.fb (A Firebase database of wrapper using aoi.fb as API)

### PR DESCRIPTION
**Pull request by guihrib**
## Type
- [ ] Bug Fix
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [x] Others: \______
  - Add database support for aoi.fb (A Firebase database of wrapper using aoi.fb as API)

Dependencies (Third Party Modules) needed: < aoi.fb| https://github.com/aoifb/aoi.fb >

Want a credit? Discord tag or other social media link: < `GR#3012` >

## Description
- Add database support for aoi.fb (A Firebase database of wrapper using aoi.fb as API)
  How to use:
- Install `aoi.fb`
- Example setup:

```js
const aoifb = require("aoi.fb")

const firebase = aoifb.Create({
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
  measurementId: ""
})

const aoijs = require("aoi.js")

const bot = new aoijs.Bot({
  token: "TOKEN", // Discord Bot Token
  prefix: "PREFIX",// Discord Bot Prefix
  intents: ["GUILDS", "GUILD_MESSAGES"], // Discord Bot Intents
  database: {
    type: "aoi.fb",
    db: firebase
  } // Change database to aoi.fb
})
```

### CODE REVIEW

**Comment by Leref** [comment]
Isn't this the same PR as before with same files?

**Comment by guihrib** [comment]
> Isn't this the same PR as before with same files?

Yes, Ayaka as I understand it was going to accept it, but he had some impediments (according to GitHub). So I remade the fork and changed what was necessary. So they can accept it. Meanwhile, I will remove the "adjust" folder and the "att.sh" requirement in aoi.fb

**Comment by Leref** [comment]
Ah I see there were conflicts likely because of previous commits made.

**Comment by guihrib** [comment]
> Ah I see there were conflicts likely because of previous commits made.

Yes, so I made the necessary changes to be able to do the pr the right way to make it easier for you in the pr

**Pull request merged**
