### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by danielpmc**
Just accept this damn PR. its accurate at this point

### CODE REVIEW

**Comment by avixityyt** [comment]
yessir , lets vote this :)

**Comment by Microwave-6443** [comment]
looks good to me, and accurate

**Comment by Dragonizedpizza** [comment]
cum

**Comment by USERSATOSHI** [comment]
welll for a package that interprete ur string into functions then execute it 
its pretty good at ram usage
plus if u know  how to manage intents and cache u can have 24 mb ram
for an aoijs bot so invalid claim

**Comment by danielpmc** [comment]
I call cap. every aoi.js bot iv seen hosted uses over 1GB ram. highest being just over 9GB ram usage

**Comment by ElTuna** [comment]
You don't know how to manage a bot ram then ._.

**Comment by danielpmc** [comment]
> @danielpmc For reference Daniel, Previous versions of aoi.js has used unneeded ram which is known among users, due to the interpreter. With recent versions, it been dropped tremendously and with the cache managing, it helps with this. Also, not many users likely use v5 as they haven't migrated because of several changes, as the entire rewrite affected their entire Bot. Overall, the upcoming version/merge will change this, as we would have a compiler and change how aoi.js runs on "string".

:O someone who noticed who i am? p.s wheres my staff role :)

**Comment by USERSATOSHI** [comment]
> I call cap. every aoi.js bot iv seen hosted uses over 1GB ram. highest being just over 9GB ram usage

#
Screenshot_2022-01-13-05-15-57-62
and u just proves yourself dumb 👏🏻 👏🏻 👏🏻

**Pull request closed without merging**
