### PR TITLE
Support of firebase database!

### PR DESCRIPTION
**Pull request by KrulDev**
## Type
- [ ] Bug Fix
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [X] Others: \ Support of firebase database using aoi.fb added!

Want a credit? Discord tag or other social media link: Luís Fernando#1581

### CODE REVIEW

**Review by guihrib — APPROVED** [review]

**Review by guihrib — APPROVED** [review]

**Comment by Leref** [comment]
Your PR changes are just allocating that aoi.js "supports" it, but we don't if the package does or not.
Since this package isn't by us, we can't fully state we support it.
It'll just be consider as a third party which is supported but not by default.
You can still use the package.

**Comment by guihrib** [comment]
> Your PR changes are just allocating that aoi.js "supports" it, but we don't if the package does or not. Since this package isn't by us, we can't fully state we support it. It'll just be consider as a third party which is supported but not by default. You can still use the package.

in the commit comment you had said it could still be used, however, it gives error when customizing the db and using aoi.fb
image

**Comment by Leref** [comment]
aoi.js main structure database is JSON, due to native support of other DB’s it won't support all unless that DB has the "right" methods for aoijs or aoijs adds those methods, I don’t use Firebase nor know much of it, but aoijs uses “tables” and other methods.
Hence that error is popping up if you read the src.
It'll actually have to be coded in aoijs to accept the other methods that DB uses.

**Comment by KrulDev** [comment]
> aoi.js main structure database is JSON, due to native support of other DB’s it won't support all unless that DB has the "right" methods for aoijs or aoijs adds those methods, I don’t use Firebase nor know much of it, but aoijs uses “tables” and other methods.
> Hence that error is popping up if you read the src.
> It'll actually have to be coded in aoijs to accept the other methods that DB uses.

Good night, I've done tests and it's working normally with firebase, this was the error returned before the edits to the aoijs code were made!

We have some users, who are already using the modified source, because they needed to use the firebase database.

**Comment by Leref** [comment]
I'll explain in simple term.
Please read the edited files, `../Database.js`
Understand aoijs using a class extend of CustomDB, 
This can already be supported by using database methods.
What you're editing is to make accepted by default which shouldn't be.

Here's an example how to use other DB's.

```
database : {
type : "database type",
db : require('package here'),
tables : ['main']
}
```

**Pull request closed without merging**
